//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

DATA LCDATA1<>+0x000(SB)/8, $0x8080808080808080
DATA LCDATA1<>+0x008(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA1<>+0x010(SB)/8, $0x0000000000000000
DATA LCDATA1<>+0x018(SB)/8, $0x0000000000000000
DATA LCDATA1<>+0x020(SB)/8, $0x0909090909090909
DATA LCDATA1<>+0x028(SB)/8, $0x0909090909090909
DATA LCDATA1<>+0x030(SB)/8, $0x0909090909090909
DATA LCDATA1<>+0x038(SB)/8, $0x0109090909090909
DATA LCDATA1<>+0x040(SB)/8, $0xf4f4f4f4f4f4f4f4
DATA LCDATA1<>+0x048(SB)/8, $0xf4f4f4f4f4f4f4f4
DATA LCDATA1<>+0x050(SB)/8, $0xf4f4f4f4f4f4f4f4
DATA LCDATA1<>+0x058(SB)/8, $0xf4f4f4f4f4f4f4f4
DATA LCDATA1<>+0x060(SB)/8, $0x0101010101010101
DATA LCDATA1<>+0x068(SB)/8, $0x0403020200000000
DATA LCDATA1<>+0x070(SB)/8, $0x0101010101010101
DATA LCDATA1<>+0x078(SB)/8, $0x0403020200000000
DATA LCDATA1<>+0x080(SB)/8, $0x0101010101010101
DATA LCDATA1<>+0x088(SB)/8, $0x0101010101010101
DATA LCDATA1<>+0x090(SB)/8, $0x0101010101010101
DATA LCDATA1<>+0x098(SB)/8, $0x0101010101010101
DATA LCDATA1<>+0x0a0(SB)/8, $0x0202020202020202
DATA LCDATA1<>+0x0a8(SB)/8, $0x0202020202020202
DATA LCDATA1<>+0x0b0(SB)/8, $0x0202020202020202
DATA LCDATA1<>+0x0b8(SB)/8, $0x0202020202020202
DATA LCDATA1<>+0x0c0(SB)/8, $0xedededededededed
DATA LCDATA1<>+0x0c8(SB)/8, $0xedededededededed
DATA LCDATA1<>+0x0d0(SB)/8, $0xedededededededed
DATA LCDATA1<>+0x0d8(SB)/8, $0xedededededededed
DATA LCDATA1<>+0x0e0(SB)/8, $0x9f9f9f9f9f9f9f9f
DATA LCDATA1<>+0x0e8(SB)/8, $0x9f9f9f9f9f9f9f9f
DATA LCDATA1<>+0x0f0(SB)/8, $0x9f9f9f9f9f9f9f9f
DATA LCDATA1<>+0x0f8(SB)/8, $0x9f9f9f9f9f9f9f9f
DATA LCDATA1<>+0x100(SB)/8, $0x8f8f8f8f8f8f8f8f
DATA LCDATA1<>+0x108(SB)/8, $0x8f8f8f8f8f8f8f8f
DATA LCDATA1<>+0x110(SB)/8, $0x8f8f8f8f8f8f8f8f
DATA LCDATA1<>+0x118(SB)/8, $0x8f8f8f8f8f8f8f8f
DATA LCDATA1<>+0x120(SB)/8, $0x8080808080808080
DATA LCDATA1<>+0x128(SB)/8, $0xf1e180c280808080
DATA LCDATA1<>+0x130(SB)/8, $0x8080808080808080
DATA LCDATA1<>+0x138(SB)/8, $0xf1e180c280808080
DATA LCDATA1<>+0x140(SB)/8, $0x8080808080808080
DATA LCDATA1<>+0x148(SB)/8, $0x90a07f7f80808080
DATA LCDATA1<>+0x150(SB)/8, $0x8080808080808080
DATA LCDATA1<>+0x158(SB)/8, $0x90a07f7f80808080
GLOBL LCDATA1<>(SB), 8, $352

TEXT ·__validate_utf8_fast_avx2(SB), $0-32

	MOVQ state+0(FP), DI
	MOVQ buf+8(FP), SI
	MOVQ len+16(FP), DX
	MOVQ res+24(FP), CX
	LEAQ LCDATA1<>(SB), BP

	LONG $0x20fa8348               // cmp    rdx, 32
	JB   LBB0_9
	LONG $0xe0428d4c               // lea    r8, [rdx - 32]
	LONG $0xc0eff9c5               // vpxor    xmm0, xmm0, xmm0
	WORD $0x3145; BYTE $0xe4       // xor    r12d, r12d
	LONG $0x597de2c4; WORD $0x0065 // vpbroadcastq    ymm4, qword 0[rbp] /* [rip + LCPI0_0] */
	LONG $0x597de2c4; WORD $0x086d // vpbroadcastq    ymm5, qword 8[rbp] /* [rip + LCPI0_2] */
	LONG $0x756ffdc5; BYTE $0x40   // vmovdqa    ymm6, yword 64[rbp] /* [rip + LCPI0_3] */
	QUAD $0x00000080856f7dc5       // vmovdqa    ymm8, yword 128[rbp] /* [rip + LCPI0_5] */
	QUAD $0x00000140b56f7dc5       // vmovdqa    ymm14, yword 320[rbp] /* [rip + LCPI0_11] */
	LONG $0x7d6f7dc5; BYTE $0x20   // vmovdqa    ymm15, yword 32[rbp] /* [rip + LCPI0_1] */
	LONG $0xd2efe9c5               // vpxor    xmm2, xmm2, xmm2
	LONG $0xef3141c4; BYTE $0xc9   // vpxor    xmm9, xmm9, xmm9
	LONG $0xffefc1c5               // vpxor    xmm7, xmm7, xmm7

LBB0_2:
	LONG $0x6f7ea1c4; WORD $0x261c // vmovdqu    ymm3, yword [rsi + r12]
	LONG $0x177de2c4; BYTE $0xdc   // vptest    ymm3, ymm4
	JNE  LBB0_4
	LONG $0x646dc1c4; BYTE $0xcf   // vpcmpgtb    ymm1, ymm2, ymm15
	LONG $0xc1ebfdc5               // vpor    ymm0, ymm0, ymm1
	LONG $0x20c48349               // add    r12, 32
	WORD $0x394d; BYTE $0xc4       // cmp    r12, r8
	JBE  LBB0_2
	JMP  LBB0_5

LBB0_4:
	LONG $0xd371f5c5; BYTE $0x04   // vpsrlw    ymm1, ymm3, 4
	LONG $0xcddbf5c5               // vpand    ymm1, ymm1, ymm5
	LONG $0x556f7dc5; BYTE $0x60   // vmovdqa    ymm10, yword 96[rbp] /* [rip + LCPI0_4] */
	LONG $0x002d62c4; BYTE $0xd1   // vpshufb    ymm10, ymm10, ymm1
	LONG $0x466d43c4; WORD $0x21da // vperm2i128    ymm11, ymm2, ymm10, 33
	LONG $0x0f2d43c4; WORD $0x0fdb // vpalignr    ymm11, ymm10, ymm11, 15
	LONG $0xd82541c4; BYTE $0xd8   // vpsubusb    ymm11, ymm11, ymm8
	LONG $0xfc2541c4; BYTE $0xda   // vpaddb    ymm11, ymm11, ymm10
	LONG $0x466dc3c4; WORD $0x21d3 // vperm2i128    ymm2, ymm2, ymm11, 33
	LONG $0x0f25e3c4; WORD $0x0ed2 // vpalignr    ymm2, ymm11, ymm2, 14
	QUAD $0x000000a095d8edc5       // vpsubusb    ymm2, ymm2, yword 160[rbp] /* [rip + LCPI0_6] */
	LONG $0xfc6dc1c4; BYTE $0xd3   // vpaddb    ymm2, ymm2, ymm11
	LONG $0x646d41c4; BYTE $0xda   // vpcmpgtb    ymm11, ymm2, ymm10
	LONG $0x643d41c4; BYTE $0xd2   // vpcmpgtb    ymm10, ymm8, ymm10
	LONG $0xef2541c4; BYTE $0xd2   // vpxor    ymm10, ymm11, ymm10
	LONG $0x4645e3c4; WORD $0x21fb // vperm2i128    ymm7, ymm7, ymm3, 33
	LONG $0x0f65e3c4; WORD $0x0fff // vpalignr    ymm7, ymm3, ymm7, 15
	QUAD $0x000000c09d7445c5       // vpcmpeqb    ymm11, ymm7, yword 192[rbp] /* [rip + LCPI0_7] */
	LONG $0xe67445c5               // vpcmpeqb    ymm12, ymm7, ymm6
	QUAD $0x000000e0ad6465c5       // vpcmpgtb    ymm13, ymm3, yword 224[rbp] /* [rip + LCPI0_8] */
	LONG $0xdb2541c4; BYTE $0xdd   // vpand    ymm11, ymm11, ymm13
	QUAD $0x00000100ad6465c5       // vpcmpgtb    ymm13, ymm3, yword 256[rbp] /* [rip + LCPI0_9] */
	LONG $0xdb1d41c4; BYTE $0xe5   // vpand    ymm12, ymm12, ymm13
	LONG $0xeb1d41c4; BYTE $0xdb   // vpor    ymm11, ymm12, ymm11
	LONG $0x463563c4; WORD $0x21c9 // vperm2i128    ymm9, ymm9, ymm1, 33
	LONG $0x0f7543c4; WORD $0x0fc9 // vpalignr    ymm9, ymm1, ymm9, 15
	QUAD $0x00000120a56f7dc5       // vmovdqa    ymm12, yword 288[rbp] /* [rip + LCPI0_10] */
	LONG $0x001d42c4; BYTE $0xe1   // vpshufb    ymm12, ymm12, ymm9
	LONG $0xff649dc5               // vpcmpgtb    ymm7, ymm12, ymm7
	LONG $0x000d42c4; BYTE $0xc9   // vpshufb    ymm9, ymm14, ymm9
	LONG $0xcb6435c5               // vpcmpgtb    ymm9, ymm9, ymm3
	LONG $0xffdbb5c5               // vpand    ymm7, ymm9, ymm7
	LONG $0xeb7dc1c4; BYTE $0xc3   // vpor    ymm0, ymm0, ymm11
	LONG $0xced865c5               // vpsubusb    ymm9, ymm3, ymm6
	LONG $0xeb7dc1c4; BYTE $0xc1   // vpor    ymm0, ymm0, ymm9
	LONG $0xc7ebfdc5               // vpor    ymm0, ymm0, ymm7
	LONG $0xc0ebadc5               // vpor    ymm0, ymm10, ymm0
	LONG $0xc96f7dc5               // vmovdqa    ymm9, ymm1
	LONG $0xfb6ffdc5               // vmovdqa    ymm7, ymm3
	LONG $0x20c48349               // add    r12, 32
	WORD $0x394d; BYTE $0xc4       // cmp    r12, r8
	JBE  LBB0_2

LBB0_5:
	WORD $0x3949; BYTE $0xd4 // cmp    r12, rdx
	JAE  LBB0_10

LBB0_6:
	LONG $0xc9eff1c5             // vpxor    xmm1, xmm1, xmm1
	LONG $0x0f7ffac5             // vmovdqu    oword [rdi], xmm1
	LONG $0x4f7ffac5; BYTE $0x10 // vmovdqu    oword [rdi + 16], xmm1
	WORD $0x8949; BYTE $0xd0     // mov    r8, rdx
	WORD $0x294d; BYTE $0xe0     // sub    r8, r12
	JE   LBB0_28
	LONG $0x260c8d4e             // lea    r9, [rsi + r12]
	LONG $0x20f88349             // cmp    r8, 32
	JB   LBB0_8
	LONG $0x161c8d48             // lea    rbx, [rsi + rdx]
	WORD $0x3948; BYTE $0xdf     // cmp    rdi, rbx
	JAE  LBB0_14
	LONG $0x071c8d4a             // lea    rbx, [rdi + r8]
	WORD $0x3949; BYTE $0xd9     // cmp    r9, rbx
	JAE  LBB0_14

LBB0_8:
	WORD $0x3145; BYTE $0xd2 // xor    r10d, r10d

LBB0_22:
	WORD $0xd389             // mov    ebx, edx
	WORD $0x2944; BYTE $0xe3 // sub    ebx, r12d
	WORD $0xff48; BYTE $0xca // dec    rdx
	WORD $0x294c; BYTE $0xd2 // sub    rdx, r10
	WORD $0x294c; BYTE $0xe2 // sub    rdx, r12
	LONG $0x03e38348         // and    rbx, 3
	JE   LBB0_25
	WORD $0xf748; BYTE $0xdb // neg    rbx

LBB0_24:
	LONG $0x04b60f43; BYTE $0x11 // movzx    eax, byte [r9 + r10]
	LONG $0x17048842             // mov    byte [rdi + r10], al
	WORD $0xff49; BYTE $0xc2     // inc    r10
	WORD $0xff48; BYTE $0xc3     // inc    rbx
	JNE  LBB0_24

LBB0_25:
	LONG $0x03fa8348             // cmp    rdx, 3
	JB   LBB0_28
	WORD $0x294d; BYTE $0xd0     // sub    r8, r10
	LONG $0x17548d4a; BYTE $0x03 // lea    rdx, [rdi + r10 + 3]
	WORD $0x014d; BYTE $0xd4     // add    r12, r10
	LONG $0x26448d4a; BYTE $0x03 // lea    rax, [rsi + r12 + 3]
	WORD $0xf631                 // xor    esi, esi

LBB0_27:
	LONG $0x305cb60f; BYTE $0xfd // movzx    ebx, byte [rax + rsi - 3]
	LONG $0xfd325c88             // mov    byte [rdx + rsi - 3], bl
	LONG $0x305cb60f; BYTE $0xfe // movzx    ebx, byte [rax + rsi - 2]
	LONG $0xfe325c88             // mov    byte [rdx + rsi - 2], bl
	LONG $0x305cb60f; BYTE $0xff // movzx    ebx, byte [rax + rsi - 1]
	LONG $0xff325c88             // mov    byte [rdx + rsi - 1], bl
	LONG $0x301cb60f             // movzx    ebx, byte [rax + rsi]
	WORD $0x1c88; BYTE $0x32     // mov    byte [rdx + rsi], bl
	LONG $0x04c68348             // add    rsi, 4
	WORD $0x3949; BYTE $0xf0     // cmp    r8, rsi
	JNE  LBB0_27
	JMP  LBB0_28

LBB0_9:
	LONG $0xffefc1c5             // vpxor    xmm7, xmm7, xmm7
	WORD $0x3145; BYTE $0xe4     // xor    r12d, r12d
	LONG $0xef3141c4; BYTE $0xc9 // vpxor    xmm9, xmm9, xmm9
	LONG $0xd2efe9c5             // vpxor    xmm2, xmm2, xmm2
	LONG $0xc0eff9c5             // vpxor    xmm0, xmm0, xmm0
	WORD $0x3949; BYTE $0xd4     // cmp    r12, rdx
	JB   LBB0_6

LBB0_10:
	LONG $0x4d64edc5; BYTE $0x20 // vpcmpgtb    ymm1, ymm2, yword 32[rbp] /* [rip + LCPI0_1] */
	LONG $0xc1ebfdc5             // vpor    ymm0, ymm0, ymm1
	JMP  LBB0_29

LBB0_14:
	WORD $0x894d; BYTE $0xc2                   // mov    r10, r8
	LONG $0xe0e28349                           // and    r10, -32
	LONG $0xe0728d4d                           // lea    r14, [r10 - 32]
	WORD $0x894c; BYTE $0xf3                   // mov    rbx, r14
	LONG $0x05ebc148                           // shr    rbx, 5
	LONG $0x015b8d44                           // lea    r11d, [rbx + 1]
	LONG $0x07e38341                           // and    r11d, 7
	LONG $0xe0fe8149; WORD $0x0000; BYTE $0x00 // cmp    r14, 224
	JAE  LBB0_16
	WORD $0xdb31                               // xor    ebx, ebx
	WORD $0x854d; BYTE $0xdb                   // test    r11, r11
	JNE  LBB0_19
	JMP  LBB0_21

LBB0_16:
	QUAD $0x000000e026b48d4e // lea    r14, [rsi + r12 + 224]
	LONG $0xff7b8d4d         // lea    r15, [r11 - 1]
	WORD $0x2949; BYTE $0xdf // sub    r15, rbx
	WORD $0xdb31             // xor    ebx, ebx

LBB0_17:
	QUAD $0xff201e8c107cc1c4; WORD $0xffff     // vmovups    ymm1, yword [r14 + rbx - 224]
	LONG $0x0c11fcc5; BYTE $0x1f               // vmovups    yword [rdi + rbx], ymm1
	QUAD $0xff401e8c107cc1c4; WORD $0xffff     // vmovups    ymm1, yword [r14 + rbx - 192]
	LONG $0x4c11fcc5; WORD $0x201f             // vmovups    yword [rdi + rbx + 32], ymm1
	QUAD $0xff601e8c107cc1c4; WORD $0xffff     // vmovups    ymm1, yword [r14 + rbx - 160]
	LONG $0x4c11fcc5; WORD $0x401f             // vmovups    yword [rdi + rbx + 64], ymm1
	LONG $0x107cc1c4; WORD $0x1e4c; BYTE $0x80 // vmovups    ymm1, yword [r14 + rbx - 128]
	LONG $0x4c11fcc5; WORD $0x601f             // vmovups    yword [rdi + rbx + 96], ymm1
	LONG $0x107cc1c4; WORD $0x1e4c; BYTE $0xa0 // vmovups    ymm1, yword [r14 + rbx - 96]
	QUAD $0x0000801f8c11fcc5; BYTE $0x00       // vmovups    yword [rdi + rbx + 128], ymm1
	LONG $0x107cc1c4; WORD $0x1e4c; BYTE $0xc0 // vmovups    ymm1, yword [r14 + rbx - 64]
	QUAD $0x0000a01f8c11fcc5; BYTE $0x00       // vmovups    yword [rdi + rbx + 160], ymm1
	LONG $0x107cc1c4; WORD $0x1e4c; BYTE $0xe0 // vmovups    ymm1, yword [r14 + rbx - 32]
	QUAD $0x0000c01f8c11fcc5; BYTE $0x00       // vmovups    yword [rdi + rbx + 192], ymm1
	LONG $0x6f7ec1c4; WORD $0x1e0c             // vmovdqu    ymm1, yword [r14 + rbx]
	QUAD $0x0000e01f8c7ffec5; BYTE $0x00       // vmovdqu    yword [rdi + rbx + 224], ymm1
	LONG $0x00c38148; WORD $0x0001; BYTE $0x00 // add    rbx, 256
	LONG $0x08c78349                           // add    r15, 8
	JNE  LBB0_17
	WORD $0x854d; BYTE $0xdb                   // test    r11, r11
	JE   LBB0_21

LBB0_19:
	WORD $0xf749; BYTE $0xdb // neg    r11

LBB0_20:
	LONG $0x6f7ec1c4; WORD $0x190c // vmovdqu    ymm1, yword [r9 + rbx]
	LONG $0x0c7ffec5; BYTE $0x1f   // vmovdqu    yword [rdi + rbx], ymm1
	LONG $0x20c38348               // add    rbx, 32
	WORD $0xff49; BYTE $0xc3       // inc    r11
	JNE  LBB0_20

LBB0_21:
	WORD $0x394d; BYTE $0xd0 // cmp    r8, r10
	JNE  LBB0_22

LBB0_28:
	LONG $0x1f6ffec5               // vmovdqu    ymm3, yword [rdi]
	LONG $0xd371f5c5; BYTE $0x04   // vpsrlw    ymm1, ymm3, 4
	LONG $0x597de2c4; WORD $0x0865 // vpbroadcastq    ymm4, qword 8[rbp] /* [rip + LCPI0_2] */
	LONG $0xccdbf5c5               // vpand    ymm1, ymm1, ymm4
	LONG $0x656ffdc5; BYTE $0x40   // vmovdqa    ymm4, yword 64[rbp] /* [rip + LCPI0_3] */
	LONG $0xecd8e5c5               // vpsubusb    ymm5, ymm3, ymm4
	LONG $0xc5ebfdc5               // vpor    ymm0, ymm0, ymm5
	LONG $0x6d6ffdc5; BYTE $0x60   // vmovdqa    ymm5, yword 96[rbp] /* [rip + LCPI0_4] */
	LONG $0x0055e2c4; BYTE $0xe9   // vpshufb    ymm5, ymm5, ymm1
	LONG $0x466de3c4; WORD $0x21f5 // vperm2i128    ymm6, ymm2, ymm5, 33
	LONG $0x0f55e3c4; WORD $0x0ff6 // vpalignr    ymm6, ymm5, ymm6, 15
	QUAD $0x00000080856f7dc5       // vmovdqa    ymm8, yword 128[rbp] /* [rip + LCPI0_5] */
	LONG $0xd84dc1c4; BYTE $0xf0   // vpsubusb    ymm6, ymm6, ymm8
	LONG $0xf5fccdc5               // vpaddb    ymm6, ymm6, ymm5
	LONG $0x466de3c4; WORD $0x21d6 // vperm2i128    ymm2, ymm2, ymm6, 33
	LONG $0x0f4de3c4; WORD $0x0ed2 // vpalignr    ymm2, ymm6, ymm2, 14
	QUAD $0x000000a095d8edc5       // vpsubusb    ymm2, ymm2, yword 160[rbp] /* [rip + LCPI0_6] */
	LONG $0xd6fcedc5               // vpaddb    ymm2, ymm2, ymm6
	LONG $0xd564edc5               // vpcmpgtb    ymm2, ymm2, ymm5
	LONG $0xed64bdc5               // vpcmpgtb    ymm5, ymm8, ymm5
	LONG $0xd5efedc5               // vpxor    ymm2, ymm2, ymm5
	LONG $0x4645e3c4; WORD $0x21eb // vperm2i128    ymm5, ymm7, ymm3, 33
	LONG $0x0f65e3c4; WORD $0x0fed // vpalignr    ymm5, ymm3, ymm5, 15
	QUAD $0x000000c0b574d5c5       // vpcmpeqb    ymm6, ymm5, yword 192[rbp] /* [rip + LCPI0_7] */
	LONG $0xe474d5c5               // vpcmpeqb    ymm4, ymm5, ymm4
	QUAD $0x000000e0bd64e5c5       // vpcmpgtb    ymm7, ymm3, yword 224[rbp] /* [rip + LCPI0_8] */
	LONG $0xf7dbcdc5               // vpand    ymm6, ymm6, ymm7
	QUAD $0x00000100bd64e5c5       // vpcmpgtb    ymm7, ymm3, yword 256[rbp] /* [rip + LCPI0_9] */
	LONG $0xe7dbddc5               // vpand    ymm4, ymm4, ymm7
	LONG $0xe6ebddc5               // vpor    ymm4, ymm4, ymm6
	LONG $0xc4ebfdc5               // vpor    ymm0, ymm0, ymm4
	LONG $0x4635e3c4; WORD $0x21e1 // vperm2i128    ymm4, ymm9, ymm1, 33
	LONG $0x0f75e3c4; WORD $0x0fcc // vpalignr    ymm1, ymm1, ymm4, 15
	QUAD $0x00000120a56ffdc5       // vmovdqa    ymm4, yword 288[rbp] /* [rip + LCPI0_10] */
	LONG $0x005de2c4; BYTE $0xe1   // vpshufb    ymm4, ymm4, ymm1
	LONG $0xe564ddc5               // vpcmpgtb    ymm4, ymm4, ymm5
	QUAD $0x00000140ad6ffdc5       // vmovdqa    ymm5, yword 320[rbp] /* [rip + LCPI0_11] */
	LONG $0x0055e2c4; BYTE $0xc9   // vpshufb    ymm1, ymm5, ymm1
	LONG $0xcb64f5c5               // vpcmpgtb    ymm1, ymm1, ymm3
	LONG $0xccdbf5c5               // vpand    ymm1, ymm1, ymm4
	LONG $0xc1ebfdc5               // vpor    ymm0, ymm0, ymm1
	LONG $0xc0ebedc5               // vpor    ymm0, ymm2, ymm0

LBB0_29:
	WORD $0xc031                 // xor    eax, eax
	LONG $0x177de2c4; BYTE $0xc0 // vptest    ymm0, ymm0
	WORD $0x940f; BYTE $0xd0     // sete    al
	WORD $0x8948; BYTE $0x01     // mov    qword [rcx], rax
	VZEROUPPER
	RET
